name: publish Npm

on:
  push:
    branches: [ publish ]


jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: npm install
      - name: Build 
        run: pnpm run build 
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_AUTH_TOKEN }}"

      - name: 'Publish to the npm registry'
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.JM_GITHUB_TOKEN }}
